spring.application.name=hayden
server.port=8085

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

blog.author.name=Hoang Dinh Hieu
blog.author.title=Backend Engineer
blog.author.email=hieuhd@kaopiz.com
blog.author.github=https://github.com/hieuhoangatm
blog.author.linkedin=https://linkedin.com/in/hieuhoangatm
blog.author.facebook=https://www.facebook.com/hdhieu863
blog.site.url=https://hayden.dev.vn
blog.site.name=Hayden.dev
